# -*- coding: utf-8 -*-
"""Sri Lanka Flood Risk.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14vxmpA3GzCMdrJ5XmoCVTaORNL1cPIj_
"""

import pandas as pd
import numpy as np

from google.colab import files

uploaded = files.upload()

df = pd.read_csv('sri_lanka_flood_risk_dataset_25000.csv')

df.head()

df.shape

df.info()

df.describe()

df.columns = df.columns.str.strip().str.lower().str.replace(' ', '_')

df.head()

df.isnull().sum()

df = df.dropna(subset=['district'])

df['monthly_rainfall_mm'] = df['monthly_rainfall_mm'].fillna(0)
df['population_density_per_km2'] = df['population_density_per_km2'].fillna(0)
df['elevation_m'] = df['elevation_m'].fillna(df['elevation_m'].median())

df.duplicated().sum()

df = df.drop_duplicates()

df['district'] = df['district'].str.strip().str.title()

df.district.unique()

# Define bins and labels for flood risk levels
bins = [0, 25, 50, 75, 101] # Bins from 0 up to 100 for flood_risk_score
labels = ['LOW', 'MEDIUM', 'HIGH', 'VERY HIGH']


# Create the 'flood_risk_level' column by categorizing 'flood_risk_score'
df['flood_risk_level'] = pd.cut(df['flood_risk_score'], bins=bins, labels=labels, right=False)


# Convert to string and apply string operations for consistency
df['flood_risk_level'] = df['flood_risk_level'].astype(str).str.strip().str.upper()

df.head()

df['flood_risk_level'] = df['flood_risk_level'].replace({
    'HIGH RISK': 'HIGH',
    'H': 'HIGH',
    'MEDIUM RISK': 'MEDIUM',
    'M': 'MEDIUM',
    'LOW RISK': 'LOW',
    'L': 'LOW'
})

df.head()

df = df[df['rainfall_7d_mm'] >= 0]

df = df[df['population_density_per_km2'] >= 0]

df = df[df['elevation_m'] >= -10]

df = df[
    (df['latitude'].between(5, 10)) &
    (df['longitude'].between(79, 82))
]

df['generation_date'] = pd.to_datetime(df['generation_date'])
df['year'] = df['generation_date'].dt.year
df['year'] = df['year'].astype(int)

df['risk_score'] = df['flood_risk_level'].map({
    'HIGH': 3,
    'MEDIUM': 2,
    'LOW': 1
})

df['population_at_risk'] = df['population_density_per_km2'] * df['risk_score']

#outlier detection
Q1 = df['rainfall_7d_mm'].quantile(0.25)
Q3 = df['rainfall_7d_mm'].quantile(0.75)
IQR = Q3 - Q1

df = df[
    (df['rainfall_7d_mm'] >= Q1 - 1.5 * IQR) &
    (df['rainfall_7d_mm'] <= Q3 + 1.5 * IQR)
]

df.info()

df.describe()

df['flood_risk_level'].value_counts()

df.to_csv('cleaned_flood_risk_data.csv', index=False)